<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://TargetNamespace.com/fileReadService"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SOA_COMPONENTS/DBAdapter/fileReadService"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/fileReadService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="employee" namespace="http://TargetNamespace.com/fileReadService"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/fileReadService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="employee" namespace="http://TargetNamespace.com/fileReadService"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 16 22:03:56 IST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:employee>
      <xsl:for-each select="/ns0:employee/ns0:detail">
        <ns0:detail>
          <ns0:EID>
            <xsl:value-of select="ns0:EID"/>
          </ns0:EID>
          <ns0:EMPLOYEE_NAME>
            <xsl:value-of select="ns0:EMPLOYEE_NAME"/>
          </ns0:EMPLOYEE_NAME>
          <ns0:ADDRESS>
            <xsl:value-of select="ns0:ADDRESS"/>
          </ns0:ADDRESS>
          <ns0:PHONE>
            <xsl:value-of select="ns0:PHONE"/>
          </ns0:PHONE>
          <ns0:STATE>
            <xsl:value-of select="ns0:STATE"/>
          </ns0:STATE>
          <ns0:C6>
            <xsl:value-of select="ns0:C6"/>
          </ns0:C6>
        </ns0:detail>
      </xsl:for-each>
    </ns0:employee>
  </xsl:template>
</xsl:stylesheet>
